### ISSUE TITLE
EPERM: operation not permitted, read error when running bun create bhvr@latest

### ISSUE THREAD

**Issue by benoitgrasset-cliq** [stevedylandev/bhvr#10]
## Description:
When trying to scaffold a new project with the command:

```bash
bun create bhvr@latest
```
I encounter the following error:

```yaml
EPERM: operation not permitted, read
      fd: 0,
 syscall: "read",
   errno: -1,
    code: "EPERM"
```

## Environment:

OS: Linux – Ubuntu 22.04.5 LTS 

Bun version: 1.2.11

## Steps to Reproduce:

Run` bun create bhvr@latest` in the terminal
